In [4]:
import tensorflow as tf
import numpy as np
import pandas as pd
import os 


data = pd.read_csv("C:/Users/ASTRONAUTA/Documents/computacion/Machine Learning/primera fase/Tweets.csv")
data_train=data[2928:]
data_val =data[:2928]

In [16]:
#files = os.listdir('C:/Users/ASTRONAUTA/Documents/Machine Learning/aclImdb/test/neg')
#os.listdir('C:/Users/ASTRONAUTA/Documents/Machine Learning/aclImdb/test/neg')

In [63]:
len(tlist_txt)


11712

In [5]:
# convertir a objetos tipo keras. El conjunto de entrenamiento y validacion 
max_features = 200
sequence_length = None
embedding_dim = 128

from tensorflow.keras.layers import TextVectorization


dtrain_lab = data_train[['airline_sentiment','negativereason']].to_numpy()
display(dtrain_lab)



tlist_txt = data_train['negativereason'].tolist()
tlist_sent = data_train['airline_sentiment'].tolist()

rac = 0

for k in tlist_txt:
    rap = tlist_txt[rac] 
    if pd.isnull(rap) == True:
        tlist_txt[rac] = 'empty'
    rac+=1


#p-prueba
p_list = []

for i in tlist_sent:
    if i == 'positive':
        p_list.append(1)
    if i == 'negative' or i == 'neutral':
        p_list.append(0)
train_sent = np.array(p_list)

val_txt = data_val['negativereason'].tolist()
val_sent = data_val['airline_sentiment'].tolist()


l_val = []

# na-numpyarray
for j in val_sent:
    if j == 'positive':
        l_val.append(1)
    if j == 'negative' or j == 'neutral':
        l_val.append(0)
sent_val_na = np.array(l_val)

dac = 0

for k in val_txt:
    hap = val_txt[dac] 
    if pd.isnull(hap) == True:
        val_txt[dac] = 'empty'
    dac+=1


tftrain_db = tf.data.Dataset.from_tensor_slices((tlist_txt, train_sent))

tfval_db = tf.data.Dataset.from_tensor_slices((val_txt, sent_val_na))

vectorize_layer = TextVectorization(
    standardize='lower_and_strip_punctuation',
    max_tokens=20000,
    output_mode="int",
    output_sequence_length=500,
)

tftrain_db=tftrain_db.batch(32)

tfval_db= tfval_db.batch(32)

tftext_db = tftrain_db.map(lambda x, y: x)
vectorize_layer.adapt(tftext_db)

#pruebas de transformar listas, datasets, etc.. en tensores
#objtf_train=tf.convert_to_tensor(train_np)

#vectorize_layer.adapt(tftrain_data)
#int_datatftrain = vectorize_layer(tftrain_data)

#vectorize_layer.adapt(train_np)
#vectorize_layer.adapt(objtf_train)
#int_train = vectorize_layer(train_np)
#print(type(int_train))
#vectorize_layer.adapt(objtf_train)
#int_tftrain = vectorize_layer(objtf_train)

#vectorize_layer.adapt(tftrain_db)
#vct_db = vectorize_layer(tftrain_db)



array([['negative', 'Customer Service Issue'],
       ['negative', 'Late Flight'],
       ['negative', 'Customer Service Issue'],
       ...,
       ['neutral', nan],
       ['negative', 'Customer Service Issue'],
       ['neutral', nan]], dtype=object)

In [6]:
raw_train_map=tftrain_db.batch(32)
raw_train_map

<BatchDataset element_spec=(TensorSpec(shape=(None, None), dtype=tf.string, name=None), TensorSpec(shape=(None, None), dtype=tf.int32, name=None))>

In [67]:
len(tftrain_db)

366

In [38]:
for i in raw_train_map:
    print(i)

(<tf.Tensor: shape=(32,), dtype=string, numpy=
array([b'Customer Service Issue', b'Late Flight',
       b'Customer Service Issue', b'Customer Service Issue',
       b'Flight Attendant Complaints', b'Late Flight',
       b'Customer Service Issue', b'Late Flight', b'empty',
       b'Flight Attendant Complaints', b'Bad Flight',
       b'Customer Service Issue', b'Late Flight', b'empty',
       b'Flight Booking Problems', b'Cancelled Flight',
       b'Flight Booking Problems', b'Late Flight',
       b'Customer Service Issue', b'empty', b'empty', b'empty', b'empty',
       b"Can't Tell", b'empty', b'Lost Luggage', b"Can't Tell",
       b'Flight Booking Problems', b'empty', b"Can't Tell", b'empty',
       b'Lost Luggage'], dtype=object)>, <tf.Tensor: shape=(32,), dtype=int32, numpy=
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0])>)
(<tf.Tensor: shape=(32,), dtype=string, numpy=
array([b'Customer Service Issue', b"Can't Tell", b'e

(<tf.Tensor: shape=(32,), dtype=string, numpy=
array([b'empty', b'empty', b'empty', b'empty', b'Late Flight', b'empty',
       b'Late Flight', b'empty', b'Late Flight', b'empty', b'empty',
       b'Late Flight', b'empty', b'empty', b'empty', b'empty',
       b'Late Flight', b'empty', b'Bad Flight', b'empty',
       b'Customer Service Issue', b'Bad Flight', b'Late Flight', b'empty',
       b'Bad Flight', b'empty', b'empty', b'empty', b'empty', b'empty',
       b'Late Flight', b'empty'], dtype=object)>, <tf.Tensor: shape=(32,), dtype=int32, numpy=
array([1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1])>)
(<tf.Tensor: shape=(32,), dtype=string, numpy=
array([b'empty', b'empty', b'empty', b'Late Flight',
       b'Customer Service Issue', b'empty', b'empty', b'Late Flight',
       b'Lost Luggage', b'empty', b'Late Flight', b'Late Flight',
       b'empty', b'empty', b'longlines', b'Late Flight', b'empty',
       b'empty', b'Customer Serv

(<tf.Tensor: shape=(32,), dtype=string, numpy=
array([b'Late Flight', b'Customer Service Issue',
       b'Customer Service Issue', b'empty', b'empty', b'empty', b'empty',
       b'empty', b'empty', b"Can't Tell", b'Lost Luggage', b'empty',
       b'empty', b'empty', b'empty', b'longlines', b'Cancelled Flight',
       b'empty', b'empty', b'empty', b'empty', b'empty',
       b'Flight Attendant Complaints', b'Customer Service Issue',
       b'Cancelled Flight', b'empty', b'Customer Service Issue', b'empty',
       b'empty', b'Cancelled Flight', b'Flight Attendant Complaints',
       b'Customer Service Issue'], dtype=object)>, <tf.Tensor: shape=(32,), dtype=int32, numpy=
array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0])>)
(<tf.Tensor: shape=(32,), dtype=string, numpy=
array([b'empty', b'Flight Attendant Complaints',
       b'Customer Service Issue', b'empty', b'Customer Service Issue',
       b'Cancelled Flight', b'empty', b'Flig

In [36]:
tftrain_db

<TensorSliceDataset element_spec=(TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=(), dtype=tf.int32, name=None))>

In [39]:
v_dbtrain

<MapDataset element_spec=(TensorSpec(shape=(None, 30), dtype=tf.int64, name=None), TensorSpec(shape=(), dtype=tf.int32, name=None))>

In [3]:
for i in v_dbtrain:
    print(v_dbtrain)

NameError: name 'v_dbtrain' is not defined

In [7]:
#vectorizacion o transformacion a vectores de objetos tipo: keras(train_set y val_set)
def vectorize_text(text, label):
    text = tf.expand_dims(text, -1)
    return vectorize_layer(text), label

# text_ds = tftrain_db.map(lambda x, y: x)
# Let's call `adapt`:


# v is for vector
v_dbtrain = tftrain_db.map(vectorize_text)
v_dbval = tfval_db.map(vectorize_text)


In [8]:

def mapas(tile):
    print(tile)
    if tile == True:
        print('hola')
    
#objtf_train=tf.convert_to_tensor(train_np)
data_train[['negativereason']]
np.empty(1,dtype = 'int')

tlist_txt = data_train['negativereason'].tolist()
tlist_sent = data_train['airline_sentiment'].tolist()

rac = 0

for k in tlist_txt:
    rap = tlist_txt[rac] 
    if pd.isnull(rap) == True:
        tlist_txt[rac] = 'empty'
    rac+=1
#print(tlist_txt)

#print(label_np)


#zap=label_np[8]
#np.isnan(zap)
#if pd.isnull(zap) == True:
#    print('problema')
#type(label_np[8])


display(v_dbtrain)
#print(val_txt)



<MapDataset element_spec=(TensorSpec(shape=(None, 500), dtype=tf.int64, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>

In [52]:
v_dbtrain

<MapDataset element_spec=(TensorSpec(shape=(None, 500), dtype=tf.int64, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>

In [51]:
v_dbval

<MapDataset element_spec=(TensorSpec(shape=(None, 500), dtype=tf.int64, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>

In [9]:
from tensorflow.keras import layers

# A integer input for vocab indices.
inputs = tf.keras.Input(shape=(None,), dtype="int64")

# Next, we add a layer to map those vocab indices into a space of dimensionality
# 'embedding_dim'.
x = layers.Embedding(max_features, embedding_dim)(inputs)
x = layers.Dropout(0.5)(x)

# Conv1D + global max pooling
x = layers.Conv1D(128, 7, padding="valid", activation="relu", strides=3)(x)
x = layers.Conv1D(128, 7, padding="valid", activation="relu", strides=3)(x)
x = layers.GlobalMaxPooling1D()(x)

# We add a vanilla hidden layer:
x = layers.Dense(128, activation="relu")(x)
x = layers.Dropout(0.5)(x)

# We project onto a single unit output layer, and squash it with a sigmoid:
predictions = layers.Dense(1, activation="sigmoid", name="predictions")(x)

model = tf.keras.Model(inputs, predictions)

# Compile the model with binary crossentropy loss and an adam optimizer.
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])


In [12]:
epochs = 3

# Fit the model using the train and test datasets.
model.fit(v_dbtrain, epochs=epochs)

Epoch 1/3
366/366 [==============================] - 70s 190ms/step - loss: 0.2595 - accuracy: 0.8362
Epoch 2/3
366/366 [==============================] - 76s 208ms/step - loss: 0.2592 - accuracy: 0.8362
Epoch 3/3
366/366 [==============================] - 82s 224ms/step - loss: 0.2592 - accuracy: 0.8362


In [61]:
c = 0
for i in v_dbval:
    print(i)
    c+=1
print(c)

(<tf.Tensor: shape=(32, 500), dtype=int64, numpy=
array([[ 2,  0,  0, ...,  0,  0,  0],
       [ 2,  0,  0, ...,  0,  0,  0],
       [ 2,  0,  0, ...,  0,  0,  0],
       ...,
       [ 2,  0,  0, ...,  0,  0,  0],
       [ 3, 14, 13, ...,  0,  0,  0],
       [ 2,  0,  0, ...,  0,  0,  0]], dtype=int64)>, <tf.Tensor: shape=(32,), dtype=int32, numpy=
array([0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0])>)
(<tf.Tensor: shape=(32, 500), dtype=int64, numpy=
array([[6, 4, 5, ..., 0, 0, 0],
       [6, 4, 5, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0],
       ...,
       [6, 4, 5, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0]], dtype=int64)>, <tf.Tensor: shape=(32,), dtype=int32, numpy=
array([0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0])>)
(<tf.Tensor: shape=(32, 500), dtype=int64, numpy=
array([[2, 0, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0

In [65]:
len(v_dbtrain)

366

In [21]:
v_dbtrain.shape

AttributeError: 'MapDataset' object has no attribute 'shape'

In [7]:
model.summary(
    line_length=None,
    positions=None,
    print_fn=None,
    expand_nested=False,
    show_trainable=False,
)


Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, None)]            0         
                                                                 
 embedding (Embedding)       (None, None, 128)         25600     
                                                                 
 dropout (Dropout)           (None, None, 128)         0         
                                                                 
 conv1d (Conv1D)             (None, None, 128)         114816    
                                                                 
 conv1d_1 (Conv1D)           (None, None, 128)         114816    
                                                                 
 global_max_pooling1d (Globa  (None, 128)              0         
 lMaxPooling1D)                                                  
                                                             

In [9]:
tftrain_db = tf.data.Dataset.from_tensor_slices((tlist_txt))
tftrain_sent = tf.data.Dataset.from_tensor_slices((train_sent))


tfval_db = tf.data.Dataset.from_tensor_slices((val_txt, sent_val_na))




In [5]:
max_features = 5000
max_len = 30

vectorize_layer = tf.keras.layers.TextVectorization(
    max_tokens=max_features,
    output_mode='int',
    output_sequence_length=max_len)

In [36]:

vectorize_layer.adapt(tlist_txt)
model = tf.keras.models.Sequential()
model.add(tf.keras.Input(shape=(1,), dtype=tf.string))
model.add(vectorize_layer)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0])